language: python
python:
- 3.6
dist: trusty
install:
- pip install -r REQUIREMENTS-DEV.txt
- pip install -e .
- pip freeze
- pip install --user codecov
script:
- set -eo pipefail
- mkdir test-reports
- make all
after_success:
- codecov
